name: Build and Publish Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/iphhra:latest,ghcr.io/${{ github.repository_owner }}/iphhra:${{ github.sha }}

  deploy_development:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Deploy development
        uses: notz/gitops-update@master
        with:
          filename: apps/templates/ip-dev.yaml
          key: spec.source.helm.valuesObject.image
          value: ghcr.io/${{ github.repository_owner }}/iphhra:${{ github.sha }}
          github-org-and-repo:  "savoiringfaire/helm"
          github-deploy-key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          commit-message: 'deploy ${{ github.sha }} to production'

  deploy_production:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy production
        uses: notz/gitops-update@master
        with:
          filename: apps/templates/ip-production.yaml
          key: spec.source.helm.valuesObject.image
          value: ghcr.io/${{ github.repository_owner }}/iphhra:${{ github.sha }}
          github-org-and-repo:  "savoiringfaire/helm"
          github-deploy-key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          commit-message: 'deploy ${{ github.sha }} to production'
